[workspace]
resolver = "2"
members = [
    "mpfs-hal",
    "mpfs-pac",
    "mpfs-hal-procmacros",
    "mpfs-hal-embassy",
    "examples",
]

exclude = ["hss-tty-flasher"]

[workspace.dependencies]
critical-section = { version = "1.2", features = ["restore-state-u8"] }

embassy-embedded-hal = { version = "0.3" }
embassy-executor = { version = "0.7", features = ["task-arena-size-8192"] }
embassy-time = { version = "0.4" }
embassy-sync = { version = "0.6" }

embedded-alloc = { version = "0.6" }
embedded-io = { version = "0.6" }
embedded-hal = "1.0"
embedded-hal-async = "1.0"

log = { version = "0.4" }
static_cell = { version = "2.1" }
