[package]
name = "examples"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
mpfs-hal = { path = "../mpfs-hal", features = ["alloc", "print"] }
embassy-time = { version = "0.4" }
mpfs-hal-embassy = { path = "../mpfs-hal-embassy", features = [] }
embassy-executor = { version = "0.7", features = ["task-arena-size-8192"] }
embedded-io = "0.6"

# SD example
sdspi = { version = "0.1", git = "https://github.com/MabezDev/embedded-fatfs.git" }
embedded-hal = "1.0"
embedded-hal-async = "1.0"
