[package]
name = "examples"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
embassy-time = { workspace = true }
embassy-executor = { workspace = true, features = ["task-arena-size-8192"] }
embedded-io = { workspace = true }
log = { workspace = true }
mpfs-hal = { path = "../mpfs-hal", features = ["alloc", "print"] }
mpfs-hal-embassy = { path = "../mpfs-hal-embassy", features = [] }

# SD example
aligned = "0.4"
sdspi = { version = "0.1", git = "https://github.com/MabezDev/embedded-fatfs.git", features = [
    "log",
] }
embedded-hal = { workspace = true }
embedded-hal-async = { workspace = true }
embassy-embedded-hal = { workspace = true }
embassy-sync = { workspace = true }
static_cell = { workspace = true }
