[package]
name = "examples"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
mpfs-hal = { path = "../mpfs-hal", features = ["alloc"] }
embassy-time = { version = "0.3", git = "https://github.com/embassy-rs/embassy.git" }
mpfs-hal-embassy = { path = "../mpfs-hal-embassy", features = [] }
embassy-executor = { version = "0.6", git = "https://github.com/embassy-rs/embassy.git", features = [
    "task-arena-size-8192",
] }
embedded-io = "0.6"
