[package]
name = "mpfs-hal"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Hardware Abstraction Layer for PolarFire SoC"
repository = "https://github.com/AlexCharlton/mpfs-hal"
categories = ["embedded", "hardware-support", "no-std"]
keywords = ["mpfs", "polarfire", "hal", "embedded-hal"]

[package.metadata.docs.rs]
default-target = "riscv64gc-unknown-none-elf"
features = ["alloc", "print", "log"]

[features]
default = ["alloc", "print", "log", "log_colors"]
debug_logs = ["print"]
log = ["print", "dep:log"]
log_colors = []
alloc = ["embedded-alloc", "embedded-io/alloc"]
print = []

[dependencies]
mpfs-pac = { version = "0.1", path = "../mpfs-pac" }
mpfs-hal-procmacros = { version = "0.1", path = "../mpfs-hal-procmacros" }
log = { version = "0.4", optional = true }
paste = "1.0"

critical-section = { workspace = true }
embedded-alloc = { version = "0.6", optional = true }
embedded-io = { version = "0.6" }
riscv = "0.12"
