[package]
name = "mpfs-hal"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Hardware Abstraction Layer for PolarFire SoC"
repository = "https://github.com/AlexCharlton/mpfs-hal"
categories = ["embedded", "hardware-support", "no-std"]
keywords = ["mpfs", "polarfire", "hal", "embedded-hal"]

[package.metadata.docs.rs]
default-target = "riscv64gc-unknown-none-elf"
features = ["alloc"]

[features]
debug_logs = []
alloc = ["embedded-alloc"]

[dependencies]
mpfs-pac = { path = "../mpfs-pac" }
mpfs-hal-procmacros = { path = "../mpfs-hal-procmacros" }

critical-section = { workspace = true }
embedded-alloc = { version = "0.6", optional = true }
riscv = "0.12"
itoa = "1.0"
